### ISSUE TITLE
What does the label in dataset mean?

### ISSUE THREAD

**Issue by VoVAllen** [zuoxingdong/VIN_PyTorch_Visdom#3]
I cannot understand what the label in the dataset is for. Could you please elaborate a little bit? Thanks.

**Comment by zuoxingdong** [comment]
@VoVAllen The labels correspond to the actions, generated by A*-planner, i.e. imitation learning.

**Comment by VoVAllen** [comment]
Still confused. It seems one grid game has only one labeled action. What's the meaning of this one action?

**Comment by kentsommer** [comment]
@VoVAllen 

For simplification assume the batch_size is 1, or in other words we only pass in a single map at a time:

The input then contains only a gridworld and the current state (S1, S2). The output of the VIN is then the best action to take (from the current state). 

So yes, the output is only a single action because after the network predicts the action it should take from the given state, you would update the current state and feed the new state back in to get the next action.

**Comment by VoVAllen** [comment]
@kentsommer Thanks for your detailed answer. It's helpful to me.
